import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { isDeepStrictEqual } from 'node:util';
import { decodeDiscoveryResumeCheckpoint } from '../../core/src/discovery-resume-checkpoint.ts';
const base=resolve('out/warm-refinement-control/n126-witness');
const load=(p)=>JSON.parse(readFileSync(p,'utf8'));
const hash=(b)=>createHash('sha256').update(b).digest('hex');
const folders=['direct','interrupted-resumed'].map((p)=>resolve(base,p));
const files=folders.map((p)=>{const pointer=load(resolve(p,'resume/latest.json')); return readFileSync(resolve(p,'resume',pointer.current.directory,'solver.bin'));});
const states=files.map(decodeDiscoveryResumeCheckpoint);
const interruption=readFileSync(resolve(base,'interruption/solver.bin'));
const interruptedState=decodeDiscoveryResumeCheckpoint(interruption);
const results=folders.map((p)=>load(resolve(p,'result.json')));
const scientificResults=results.map(({wallSeconds,peakRssBytes,startedAt,finishedAt,...rest})=>rest);
const scientificEvents=folders.map((p)=>readFileSync(resolve(p,'events.jsonl'),'utf8').trim().split(/\r?\n/).map((line)=>{const {rssBytes,...rest}=JSON.parse(line);return rest;}));
const snapshots=results[0].spatialSnapshots.map(({path})=>{const b=folders.map((p)=>readFileSync(resolve(p,path)));return {path,bytes:b[0].length,hashes:b.map(hash),equal:b[0].equals(b[1])};});
const output={recomputedAt:new Date().toISOString(),finalCheckpoint:{equal:files[0].equals(files[1]),bytes:files[0].length,hashes:files.map(hash),decodedTicks:states.map((s)=>s.tick)},interruptedCheckpoint:{decodedTick:interruptedState.tick,hash:hash(interruption)},scientificResultsEqual:isDeepStrictEqual(...scientificResults),scientificEventsEqual:isDeepStrictEqual(...scientificEvents),eventCounts:scientificEvents.map((e)=>e.length),cycles:results.map((r)=>r.cycles),stopReasons:results.map((r)=>r.stopReason),allConverged:results.every((r)=>r.allRelaxationsConverged),integrityErrors:results.map((r)=>r.integrityErrors),snapshots};
output.passed=output.finalCheckpoint.equal&&states.every((s)=>s.tick===3)&&interruptedState.tick===1&&output.scientificResultsEqual&&output.scientificEventsEqual&&output.eventCounts.every((n)=>n===3)&&output.allConverged&&output.integrityErrors.every((e)=>e.length===0)&&snapshots.length>0&&snapshots.every((s)=>s.equal);
writeFileSync('out/warm-refinement-control/review-witness.json',JSON.stringify(output,null,2)+'\n');
console.log(JSON.stringify(output));
if(!output.passed) process.exitCode=1;
